In [2]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
7    60  Female     Poor    School       Yes
29   83  Female  Average        UG       Yes
16   59    Male     Poor        UG       Yes
20   57  Female  Average    School       Yes
8    65  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1),
                                                    df['purchased'],
                                                    test_size=0.3,
                                                    random_state=0)

In [8]:
X_train

     review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [9]:
y_train

7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
15     No
30     No
32    Yes
16    Yes
42    Yes
20    Yes
43     No
8      No
13     No
25     No
5     Yes
17    Yes
40     No
49     No
1      No
12     No
37    Yes
24    Yes
6      No
23     No
36    Yes
21     No
19    Yes
9     Yes
39     No
46     No
3      No
0      No
47    Yes
44     No
Name: purchased, dtype: object

In [10]:
X_train

     review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [14]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
X_train = oe.transform(X_train)

In [16]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

In [20]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [22]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [23]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

# One Hot Encoding

In [4]:
df = pd.read_csv('customer.csv')

In [5]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [7]:
df['gender'].value_counts()

gender
Female    29
Male      21
Name: count, dtype: int64

In [8]:
df.shape

(50, 5)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder(sparse_output=False)

In [11]:
new_data = ohe.fit_transform(df[['gender']])

In [12]:
new_data

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [14]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [37]:
pd.get_dummies(df, columns=['gender'])

    age   review education purchased  gender_Female  gender_Male
0    30  Average    School        No           True        False
1    68     Poor        UG        No           True        False
2    70     Good        PG        No           True        False
3    72     Good        PG        No           True        False
4    16  Average        UG        No           True        False
5    31  Average    School       Yes           True        False
6    18     Good    School        No          False         True
7    60     Poor    School       Yes           True        False
8    65  Average        UG        No           True        False
9    74     Good        UG       Yes          False         True
10   98     Good        UG       Yes           True        False
11   74     Good        UG       Yes          False         True
12   51     Poor    School        No          False         True
13   57  Average    School        No           True        False
14   15     Poor        PG       Yes          False         True
15   75     Poor        UG        No          False         True
16   59     Poor        UG       Yes          False         True
17   22     Poor        UG       Yes           True        False
18   19     Good    School        No          False         True
19   97     Poor        PG       Yes          False         True
20   57  Average    School       Yes           True        False
21   32  Average        PG        No          False         True
22   18     Poor        PG       Yes           True        False
23   96     Good    School        No           True        False
24   16  Average        PG       Yes           True        False
25   57     Good    School        No           True        False
26   53     Poor        PG        No           True        False
27   69     Poor        PG        No           True        False
28   48     Poor    School        No          False         True
29   83  Average        UG       Yes           True        False
30   73  Average        UG        No          False         True
31   22     Poor    School       Yes           True        False
32   92  Average        UG       Yes          False         True
33   89     Good        PG       Yes           True        False
34   86  Average    School        No          False         True
35   74     Poor    School       Yes          False         True
36   34     Good        UG       Yes           True        False
37   94  Average        PG       Yes          False         True
38   45     Good    School        No           True        False
39   76     Poor        PG        No          False         True
40   39     Good    School        No          False         True
41   23     Good        PG       Yes          False         True
42   30     Good        PG       Yes           True        False
43   27     Poor        PG        No          False         True
44   77  Average        UG        No           True        False
45   61     Poor        PG       Yes          False         True
46   64     Poor        PG        No           True        False
47   38     Good        PG       Yes           True        False
48   39     Good        UG       Yes           True        False
49   25     Good        UG        No           True        False