In [1]:
print("Pandas")

Pandas

In [3]:
import pandas as pd

In [ ]:
[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]

## Introducation to DataFrame

In [6]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]], columns=["A", "B", "C"], index=["Row1", "Row2", "Row3", "Row4", "Row5"])

In [7]:
df

       A   B   C
Row1   1   2   3
Row2   4   5   6
Row3   7   8   9
Row4  10  11  12
Row5  13  14  15

In [10]:
df.head()

       A   B   C
Row1   1   2   3
Row2   4   5   6
Row3   7   8   9
Row4  10  11  12
Row5  13  14  15

In [12]:
df.tail(2)

       A   B   C
Row4  10  11  12
Row5  13  14  15

In [13]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [14]:
df.columns.to_list()

['A', 'B', 'C']

In [15]:
df.index

Index(['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], dtype='object')

In [16]:
df.index.to_list()

['Row1', 'Row2', 'Row3', 'Row4', 'Row5']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 160.0+ bytes

In [18]:
df.describe()

               A          B          C
count   5.000000   5.000000   5.000000
mean    7.000000   8.000000   9.000000
std     4.743416   4.743416   4.743416
min     1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000
50%     7.000000   8.000000   9.000000
75%    10.000000  11.000000  12.000000
max    13.000000  14.000000  15.000000

In [19]:
df.nunique()

A    5
B    5
C    5
dtype: int64

In [20]:
df["A"]

Row1     1
Row2     4
Row3     7
Row4    10
Row5    13
Name: A, dtype: int64

In [ ]:
df["A"].nunique()

5

In [22]:
df["A"].unique()

array([ 1,  4,  7, 10, 13], dtype=int64)

In [23]:
df.shape

(5, 3)

In [24]:
df.size

15

## Loading in DataFrame from CSV file

In [13]:
coffee = pd.read_csv("warmup-data\\coffee.csv")

In [34]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [36]:
results = pd.read_parquet("data\\results.parquet")

In [37]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [40]:
bios = pd.read_csv("data\\bios.csv")

In [42]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [10]:
olympics_data = pd.read_excel("data\\olympics-data.xlsx", sheet_name="bios")

In [11]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

## Accessing Data with pandas

In [14]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [15]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [20]:
coffee.sample(5)

         Day Coffee Type  Units Sold
6   Thursday    Espresso          40
7   Thursday       Latte          30
3    Tuesday       Latte          20
8     Friday    Espresso          45
12    Sunday    Espresso          45

In [26]:
#loc

coffee.loc[1]
coffee.loc[1, "Coffee Type"]
coffee.loc[1:3, "Coffee Type"]
coffee.loc[[1,2,3]]

       Day Coffee Type  Units Sold
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

### iloc

In [29]:
coffee.iloc[0]
coffee.iloc[0,1]

'Espresso'

In [33]:
coffee.iloc[:, [0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [34]:
coffee.index = coffee["Day"]

In [35]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [37]:
coffee.loc["Monday", "Coffee Type"]

Day
Monday    Espresso
Monday       Latte
Name: Coffee Type, dtype: object

## Setting Values with pandas

In [ ]:
coffee = pd.read_csv("warmup-data\\coffee.csv")

In [39]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [40]:
coffee.loc[1:3, ["Coffee Type"]] = 10

In [41]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday          10          15
2    Tuesday          10          30
3    Tuesday          10          20
4  Wednesday    Espresso          35

In [42]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [43]:
coffee["Coffee Type"]

0     Espresso
1           10
2           10
3           10
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: object

## Sort Values with pandas

In [49]:
coffee = pd.read_csv("warmup-data\\coffee.csv")

In [50]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [55]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[1,1])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [56]:
for index, row in coffee.iterrows():
    print(f"index: {index}")
    print(f"Row data:\n {row}")
    print(f"Coffee Type: {row['Coffee Type']}")
    print("------")

index: 0
Row data:
 Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
Coffee Type: Espresso
------
index: 1
Row data:
 Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object
Coffee Type: Latte
------
index: 2
Row data:
 Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object
Coffee Type: Espresso
------
index: 3
Row data:
 Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object
Coffee Type: Latte
------
index: 4
Row data:
 Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
Coffee Type: Espresso
------
index: 5
Row data:
 Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
Coffee Type: Latte
------
index: 6
Row data:
 Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
Coffee Type: Espresso
------
index: 7
Row data:
 Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
Coffee Type: Latte
------
index: 8
Row data:
 Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
Coffee Type: Espresso
------
index: 9
Row data:
 Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
Coffee Type: Latte
------
index: 10
Row data:
 Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
Coffee Type: Espresso
------
index: 11
Row data:
 Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
Coffee Type: Latte
------
index: 12
Row data:
 Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
Coffee Type: Espresso
------
index: 13
Row data:
 Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
Coffee Type: Latte
------

## Filtering Data with pandas

In [57]:
bios = pd.read_csv("data\\bios.csv")

In [58]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [59]:
bios.shape

(145500, 10)

In [61]:
temp = bios.loc[bios["height_cm"] > 215]

In [62]:
temp.shape

(35, 10)

In [64]:
bios.loc[bios["height_cm"] > 215, ["name", "height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

## Short hand syntax for filtering data with pandas (without loc)

In [65]:
bios[bios["height_cm"] > 215][["name", "height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

## Multiple filter conditions with pandas

In [66]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [67]:
bios[(bios["height_cm"] > 215) & (bios["weight_kg"] < 100)][["name", "height_cm", "weight_kg"]]

                 name  height_cm  weight_kg
5796    Andy Campbell      218.0       93.0
130461        Zhou Qi      217.0       95.0

## Filter by string conditions with pandas

In [68]:
bios[bios['name'].str.contains("keith", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

### Query Functions

In [69]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [71]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

## Adding/Removing Columns with pandas

In [72]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [73]:
coffee["price"] = 4.99

In [74]:
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [75]:
import numpy as np

In [77]:
coffee["new_price"] = np.where(coffee["Coffee Type"] == "Espresso", 3.99, 5.99)

In [78]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [79]:
coffee.drop(columns=["price"])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [80]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [81]:
coffee.drop(columns=["price"], inplace=True)

In [82]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [83]:
coffee["revenue"] = coffee["Units Sold"] * coffee["new_price"]

In [84]:
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

In [85]:
coffee.rename(columns={"new_price": "price"}, inplace=True)

In [86]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [87]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [88]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [89]:
bios["died_datetime"] = pd.to_datetime(bios["died_date"])

In [90]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  died_datetime  33940 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 12.2+ MB

In [93]:
bios["died_year"] = bios["died_datetime"].dt.month

In [94]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0

In [95]:
bios.to_csv("data\\temp_bios.csv", index=False)

In [96]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0

In [97]:
def categorize_athlete(row):
    if row["height_cm"] < 175 and row["weight_kg"] < 70:
        return "Lightweight"
    elif row["height_cm"] < 185 and row["weight_kg"] <= 80:
        return "Middleweight"
    else:
        return "Heavyweight"

In [98]:
bios["Category"] = bios.apply(categorize_athlete, axis=1)

In [99]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0,Heavyweight

## Merging and Concatenating DataFrames with pandas

In [100]:
nocs = pd.read_csv("data\\noc_regions.csv")

In [101]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [102]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0,Heavyweight

In [103]:
bios_new = pd.merge(bios, nocs, on ="NOC", how="left")

In [104]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year,Category,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0,Heavyweight,NaN,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN,Middleweight,NaN,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0,Middleweight,NaN,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0,Lightweight,NaN,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0,Heavyweight,NaN,NaN

## Handling Missing Data with pandas

In [105]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [106]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     0
price          0
revenue        0
dtype: int64

In [110]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [111]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  Unit Sold
0     Monday    Espresso        25.0   3.99    99.75        NaN
1     Monday       Latte        15.0   5.99    89.85        NaN
2    Tuesday    Espresso         NaN   3.99   119.70        NaN
3    Tuesday       Latte         NaN   5.99   119.80        NaN
4  Wednesday    Espresso        35.0   3.99   139.65        NaN

In [112]:
coffee.isnull().sum()

Day             0
Coffee Type     0
Units Sold      2
price           0
revenue         0
Unit Sold      14
dtype: int64

In [113]:
coffee["Units Sold"].fillna(coffee["Units Sold"].mean(), inplace=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_17820\2894660123.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  coffee["Units Sold"].fillna(coffee["Units Sold"].mean(), inplace=True)

In [114]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  Unit Sold
0     Monday    Espresso   25.000000   3.99    99.75        NaN
1     Monday       Latte   15.000000   5.99    89.85        NaN
2    Tuesday    Espresso   34.166667   3.99   119.70        NaN
3    Tuesday       Latte   34.166667   5.99   119.80        NaN
4  Wednesday    Espresso   35.000000   3.99   139.65        NaN

In [115]:
coffee.isnull().sum()

Day             0
Coffee Type     0
Units Sold      0
price           0
revenue         0
Unit Sold      14
dtype: int64

In [116]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [117]:
coffee.isnull().sum()

Day             0
Coffee Type     0
Units Sold      2
price           0
revenue         0
Unit Sold      14
dtype: int64

In [119]:
coffee.dropna(subset=["Units Sold"], inplace=True)

In [120]:
coffee.isnull().sum()

Day             0
Coffee Type     0
Units Sold      0
price           0
revenue         0
Unit Sold      12
dtype: int64

## Aggregating Data with pandas

In [121]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,died_datetime,died_year,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,10.0,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,7.0,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,3.0,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,7.0,Heavyweight

In [122]:
bios["born_city"].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

## Groupby Operations with pandas

In [123]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  Unit Sold
0     Monday    Espresso        25.0   3.99    99.75        NaN
1     Monday       Latte        15.0   5.99    89.85        NaN
4  Wednesday    Espresso        35.0   3.99   139.65        NaN
5  Wednesday       Latte        25.0   5.99   149.75        NaN
6   Thursday    Espresso        40.0   3.99   159.60        NaN

In [124]:
coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    235.0
Latte       175.0
Name: Units Sold, dtype: float64

# Pivot Tables with pandas

In [125]:
pivot = coffee.pivot_table(values="revenue", index="Day", columns="Coffee Type")

In [126]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Wednesday      139.65  149.75